"""Relationship attributes

Revision ID: ab5e23657ca2
Revises: 6234968212db
Create Date: 2023-11-04 10:39:12.215483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab5e23657ca2'
down_revision: Union[str, None] = '6234968212db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unittype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fuelfill', sa.Column('local_total_price', sa.Numeric(precision=7, scale=3), nullable=False))
    op.add_column('fuelfill', sa.Column('account_total_price', sa.Numeric(precision=7, scale=3), nullable=False))
    op.drop_column('fuelfill', 'local_price_per_unit')
    op.drop_column('fuelfill', 'account_price_per_unit')
    op.add_column('unit', sa.Column('type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'unit', 'unittype', ['type_id'], ['id'])
    op.add_column('vehicle', sa.Column('unit_category_id', sa.Integer(), nullable=False))
    op.drop_constraint('vehicle_ibfk_4', 'vehicle', type_='foreignkey')
    op.create_foreign_key(None, 'vehicle', 'unitcategory', ['unit_category_id'], ['id'])
    op.drop_column('vehicle', 'default_fuel_unit_id')
    op.add_column('vehiclecategory', sa.Column('meter_unit_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('vehiclecategory_ibfk_1', 'vehiclecategory', type_='foreignkey')
    op.create_foreign_key(None, 'vehiclecategory', 'unittype', ['meter_unit_type_id'], ['id'])
    op.drop_column('vehiclecategory', 'meter_unit_category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiclecategory', sa.Column('meter_unit_category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehiclecategory', type_='foreignkey')
    op.create_foreign_key('vehiclecategory_ibfk_1', 'vehiclecategory', 'unitcategory', ['meter_unit_category_id'], ['id'])
    op.drop_column('vehiclecategory', 'meter_unit_type_id')
    op.add_column('vehicle', sa.Column('default_fuel_unit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicle', type_='foreignkey')
    op.create_foreign_key('vehicle_ibfk_4', 'vehicle', 'unit', ['default_fuel_unit_id'], ['id'])
    op.drop_column('vehicle', 'unit_category_id')
    op.drop_constraint(None, 'unit', type_='foreignkey')
    op.drop_column('unit', 'type_id')
    op.add_column('fuelfill', sa.Column('account_price_per_unit', mysql.DECIMAL(precision=7, scale=3), nullable=False))
    op.add_column('fuelfill', sa.Column('local_price_per_unit', mysql.DECIMAL(precision=7, scale=3), nullable=False))
    op.drop_column('fuelfill', 'account_total_price')
    op.drop_column('fuelfill', 'local_total_price')
    op.drop_table('unittype')
    # ### end Alembic commands ###
